"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x=)qihi43fy*7+=n)k40imbi6@@2m_6#ppincz3e(#@2y)l9@t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    'payment.apps.PaymentConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'shop/templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # устанавливает булевы
                        # переменные debug и sql_queries в контексте, представляющие
                        # список SQL запросов, исполняемых в запросе
                'django.template.context_processors.request', # устанавливает переменную
                        # request в контексте
                'django.contrib.auth.context_processors.auth', # устанавливает переменную
                        # user в запросе
                'django.contrib.messages.context_processors.messages', # устанавливает
                        # переменную messages в контексте, содержащую все сообщения,
                        # сгенерированные с использованием фреймворка сообщений
                'cart.context_processors.cart', # Процессор контекста переменной cart
                        # будет исполняться всякий раз, когда шаблон прорисовывается с использованием
                        # встроенного в Django контекстного класса RequestContext
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Это путь в проекте, где хранятся статические файлы
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ***** Медиа хранилище ***** #
# Параметр MEDIA_URL – это базовый URL-адрес, по которому раздаются
# закачанные пользователями медиафайлы
MEDIA_URL = 'media/'
# Параметр MEDIA_ROOT– это локальный путь, по которому эти файлы
# находятся и который следует формировать динамически, добавляя
# значение переменной BASE_DIR в качестве префикса
MEDIA_ROOT = BASE_DIR / 'media'

# Это ключ, который будет использоваться для
# хранения корзины в пользовательском сеансе
CART_SESSION_ID = 'cart'

# *** Конфигурация сервера электронной почты ***
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

EMAIL_HOST_USER = 'mitka.lut1y@yandex.ru'
EMAIL_HOST_PASSWORD = 'hqebulvokcqpkjpy'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER

# Настроечные параметры Stripe
STRIPE_PUBLISHABLE_KEY = 'pk_test_51Ra1hwJM1Cr4eCeVrVC4VPaqnhGqr4KTlWZpdtwZrweabBAibWo8KUsw2HqFmml8IJYixHiJkMBwP5FgK7XSDBj100yLIb2e9A' # Публикуемый ключ
STRIPE_SECRET_KEY = 'sk_test_51Ra1hwJM1Cr4eCeVnQLObb3yHdfo97vJhZZBTXxpOdOOE1tcuNEJvxHzL1AIXiqbm1Zf4iq1eAgHapmcQ8orh47E006NZRTBeS' # Секретный ключ
STRIPE_API_VERSION = '2024-06-20'

STRIPE_WEBHOOK_SECRET = 'whsec_6d4e9d37ab90f4f83782c4bc1b47355076623bb1d2377a17f8cd8db180cf9025'

